name: Test
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  regression:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - uses: VirtusLab/scala-cli-setup@v1
        with:
          version: '1.14.0'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: make lint
      - run: make test
      - run: git diff --exit-code
